### ISSUE TITLE
Improve GitHub workflows we use learning from Guava CI

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/config#367]
https://github.com/google/guava/blob/master/.github/workflows/ci.yml

One of the things we can adopt is cancelling a previous run to the same branch:

```
    steps:
      # Cancel any previous runs for the same branch that are still running.
      - name: 'Cancel previous runs'
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
```
